# Generated by Django 2.0.3 on 2018-10-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twipin', '0002_curtida'),
    ]

    operations = [
        migrations.AddField(
            model_name='twip',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='twip',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
